
[window]
dimensions = { columns = 200, lines = 50 }
opacity = 0.75
blur = true

[font]
normal = { family = "FiraCode Nerd Font" }
size = 12

[general]
import = [
"~/.dotfiles/alacritty/themes/night_owl.toml"
]
